const swaggerAutogen = require('swagger-autogen')()
const endpoint = require("./routes/answers")


const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "User",
            "description": "Endpoints"
        }
    ]
}

const outputFile = './swagger_output.json'
const endpointsFiles = ["./routes/answers.js"]

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./index')
    // Your project's root file
})