const swaggerAutogen = require('swagger-autogen')()

const doc = {
    info: {
        version: "1.0.0",
        title: "Wisconsin Lutheran College Math Placement Test",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json']

}

const outputFile = './swagger_output.json'
const endpointsFiles = ['./routes/answers.js', './routes/health.js', './routes/past_courses.js', './routes/question_type.js', './routes/questions.js', './routes/student_answers.js', './routes/student_past_courses.js', './routes/students.js', './routes/test_questions.js', './routes/tests']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./index')
    // Your project's root file
})